{{- $app := index .Values "app" | default dict }}
{{- $msg := index $app "messaging" | default dict }}
{{- $rq := index $msg "rabbitmq" | default dict }}
{{- $sec := index $rq "secret" | default dict }}
{{- if index $sec "create" | default true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $sec "name" | default "orders-rabbitmq" }}
data:
  {{- if index $sec "username" }}
  RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME: {{ index $sec "username" | b64enc | quote }}
  {{- end }}
  {{- if index $sec "password" }}
  RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD: {{ index $sec "password" | b64enc | quote }}
  {{- end }}
{{- end }}