apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: locust

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: locust-config
    files:
      - locustfile.py
    options:
      disableNameSuffixHash: true
