apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: locust
  labels:
    app.kubernetes.io/name: locust
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: web
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: locust
