apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-catalog-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/k5sha/retail-store-sample-app-exit.git
    targetRevision: staging
    path: src/catalog/chart
    helm:
      values: |
        image:
          repository: 718286622836.dkr.ecr.eu-central-1.amazonaws.com/retail-store-retail-store-sample-catalog
          tag: stg-f4f1826
  destination:
    server: https://kubernetes.default.svc
    namespace: catalog-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

