apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-checkout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/k5sha/retail-store-sample-app-exit.git # заміни на свій URL, якщо інший
    targetRevision: main
    path: src/checkout/chart
    helm:
      values: |
        image:
          repository: 718286622836.dkr.ecr.eu-central-1.amazonaws.com/retail-store-retail-store-sample-checkout
          tag: prod-9303a8d
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 10
          targetCPUUtilizationPercentage: 70
  destination:
    server: https://kubernetes.default.svc
    namespace: checkout
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

