apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-ui-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/k5sha/retail-store-sample-app-exit.git
    targetRevision: main
    path: src/ui/chart
    helm:
      releaseName: retail-store-ui-prod
      values: |
        image:
          repository: 718286622836.dkr.ecr.eu-central-1.amazonaws.com/retail-store-retail-store-sample-ui
          tag: prod-362b88c
          pullPolicy: Always
        podAnnotations:
          app/buildId: "1"
        service:
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
  destination:
    server: https://kubernetes.default.svc
    namespace: ui-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

