apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-ui-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/k5sha/retail-store-sample-app-exit.git
    targetRevision: staging
    path: src/ui/chart
    helm:
      releaseName: retail-store-ui-staging
      values: |
        image:
          repository: 718286622836.dkr.ecr.eu-central-1.amazonaws.com/retail-store-retail-store-sample-ui
          tag: stg-f853816
          pullPolicy: Always
        podAnnotations:
          app/buildId: "1"
        resources:
          limits:
            memory: 768Mi
          requests:
            cpu: 128m
            memory: 512Mi
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 10
          targetCPUUtilizationPercentage: 70
        service:
          type: LoadBalancer
          port443: true
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
            external-dns.alpha.kubernetes.io/hostname: staging.zipzip.online
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:718286622836:certificate/69b24b7b-e73c-43c1-a71f-50ec622dd9dc
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  destination:
    server: https://kubernetes.default.svc
    namespace: ui-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
