apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-run-as-non-root
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: containers-must-run-as-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Containers must set securityContext.runAsNonRoot=true."
        foreach:
          - list: "request.object.spec.containers"
            pattern:
              securityContext:
                runAsNonRoot: true